### ISSUE TITLE
SIGSEGV from example code

### ISSUE THREAD

**Issue by vercingetorx** [ul/soundio#2]
When running the sine example I get:

Traceback (most recent call last)
/home/xioren/Documents/coding/nim/burner.nim(125) burner
/home/xioren/Documents/coding/nim/burner.nim(97) newOutStream
/home/xioren/Documents/coding/nim/burner.nim(94) =destroy
/usr/lib/nim/system/alloc.nim(968) dealloc
/usr/lib/nim/system/alloc.nim(829) rawDealloc
/usr/lib/nim/system/alloc.nim(376) isSmallChunk
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

Is there a particular compiler flag that is required?

**Comment by ul** [comment]
Thanks for reporting. Apparently, something changed in the Nim compiler (I guess it's related to the work on move semantics) and the destructor on OutStream is now called straight away after its creation when we return it wrapped into the Result. I don't have much interest in diving into this potentially compiler bug so I just updated the example to get rid of Result.
